// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAZwyLGBGP31ItnTXRJ2rO0sDjFlx2nJOU',
    appId: '1:356229379452:web:03310efbbaf56f6dd520f9',
    messagingSenderId: '356229379452',
    projectId: 'trendz-f91cb',
    authDomain: 'trendz-f91cb.firebaseapp.com',
    storageBucket: 'trendz-f91cb.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA93kBsTaCiPGeqfxQ6gEQ7wtclwCcWblk',
    appId: '1:356229379452:android:b346e6ea3c4c565cd520f9',
    messagingSenderId: '356229379452',
    projectId: 'trendz-f91cb',
    storageBucket: 'trendz-f91cb.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDT2W9GI_uVcBX1_CrbvK5fJKWBwSHdWd0',
    appId: '1:356229379452:ios:59956ce03e285867d520f9',
    messagingSenderId: '356229379452',
    projectId: 'trendz-f91cb',
    storageBucket: 'trendz-f91cb.appspot.com',
    iosClientId: '356229379452-rmn841ei27u3qd1no2f0ta93esq4spe1.apps.googleusercontent.com',
    iosBundleId: 'com.example.trendzApp',
  );
}
